site_name: Learning Centre
site_url: https://learn.verifa.io
site_description: >-
  Learning technologies relevant to Continuous & Cloud practices through tutorials created by Verifa

# Repository
repo_name: verifa/learn
repo_url: https://github.com/verifa/learn

# Copyright
copyright: Copyright &copy; 2023 Verifa

# Theme
theme:
  name: material

  # logo: assets/logo/terraplate-short-white.svg
  # favicon: assets/favicon.png
  font:
    text: Outfit
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    #- navigation.expand
    - content.code.annotate
    - toc.follow

# Plugins
plugins:
  - awesome-pages
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/verifa
    # - icon: fontawesome/brands/docker
    #   link: https://hub.docker.com/r/verifa/terraplate/

extra_css:
  - stylesheets/theme.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: ./docs
  - pymdownx.superfences
  - meta
  - toc:
      permalink: true
