apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-verinotes
  namespace: verinotes
spec:
  # Mount path of the secrets backend
  mount: database
  # Path to the secret
  path: creds/verinotes
  # Where to store the secrets
  destination:
    create: true
    name: vso-postgres-creds
  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: verinotes-deployment
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: verinotes-auth-dynamic
