---
apiVersion: v1
kind: Service
metadata:
  name: verinotes
  labels:
    app: verinotes
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: verinotes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verinotes-deployment
  labels:
    app: verinotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verinotes
  template:
    metadata:
      labels:
        app: verinotes
    spec:
      containers:
      - name: verinotes
        image: github.com/verifa/verinotes:v0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: VN_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: vso-postgres-creds
              key: username
        - name: VN_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vso-postgres-creds
              key: password
        - name: VN_POSTGRES_HOST
          value: postgres-postgresql.verinotes.svc.cluster.local
        args: ["server"]
        ports:
        - containerPort: 3000

